

spring:

  redis:
    host: 39.106.82.217
    port: 6379
    password: HJC916924
    database: 2
#    lettuce:
#      pool:
#        max-idle: 8

  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/finally_system02?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: HJC916924
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      maxActive: 20
      maxWait: 60000
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 1000000000
      max-request-size: 2000000000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.cslg.entity
  global-config:
    db-config:
      id-type: id_worker
server:
  port: 8001

logging:
  level:
    com.cslg.mapper: info
